description:
fields:
  ostype: |
    OS type determines how to run certain cloud-config sections, such as packages.
    Two ostypes are provided:
    - alpine, for alpine distributions.  Uses apk commands to add packages.
    - debian, for debian-based distributions.  Uses apt-get commands to add packages.
  
  image: The image name used for launching an instance.

  origin:
    The name of an instance and a snapshot to clone a new instance from.
    It has the form container/snapshot

  device-template: |
    The name of an instance, whose filesystem devices are copied to a new instance.
    The devices are copied using rsync.    
    The devices are copied from the filesystems specified in SourceConfig, or this config.

  device-origin: |
    device-origin specifies a snapshot to use to clone filesystems from.
    It has the form instance@snapshot
    snapshot is the short snapshot name
    
    Example:
    config.yaml:
      device-origin: a@copy
      filesystems:
        host:
          pattern: z/host/(instance)
    
    The command:
      lxops launch -name b config.yaml
    
    will create the b filesystem like this:
      zfs clone z/host/a@copy z/host/b
  
  source-config: |
    source-config specifies an alternate config file to use
    to determine the parameters of the "source" instance.
    The source instance is the instance used to clone or copy devices from.
    source-config is used with device-template, device-origin.
    If source-config is not specified, then the source config is the same
    as the current config.
    
    Example:
    config source.yaml has:
      filesystems:
        host:
          pattern: (fsroot)/(instance)
      properties:
        fsroot: z/host
            
    config test.yaml has:
      device-template: a
      source-config: source.yaml
      filesystems:
        host:
          pattern: (fsroot)/(instance)
      properties:
        fsroot: z/test
          
    you run:
      lxops launch -name b test.yaml
    
    This will copy a to b like this:
      rsync -av /z/host/a/ /z/test/a/
      
    The source directory is determined from the source config (source.yaml).
    The destination directory is determined from the current config (test.yaml).
        
  profiles: |
    The profiles that an instance will be launched with.
    An extra lxops profile will always be added.
  
  cloud-config-files: |
    A list of cloud-config files to apply to an instance when launching or rebuilding.
    The files can be specified using absolute paths or paths relative to the enclosing lxops file.
  
  include: |
    A list of lxops files to include.
    Include paths are either absolute or relative to the path of the including lxops file.
    The lxops files are merged in postorder traversal into a single lxops file.
    The included files are merged first, in the order that they were specified, and the 
     as follows:
    []string types are appended.  The field values of the parent lxops file are appended last.
    map types are merged in order in the natural way.  The parent lxops map entries are added last,
    overriding any previously set map keys.
    For single-valued fields a non-empty value from a later lxops file
  
  profile-pattern: |
    Specifies how the instance profile should be named.
    It defaults to "(instance).lxops"
  
  device-owner: |
    The owner (uid:gid) for new devices.
    Used to set the permissions of device directories that are created for the instance
    
  filesystems: |
    Filesystems are zfs filesystems or plain directories that are created
    when an instance is created.
    Devices are usually created inside filesystems.
    
    The keys in the filesystems map are used in the devices section
    to reference each filesystem.
  
  devices: |
    Devices are disk devices that are are attached to the instance.
    They added to the instance profile, which is attached to the instance.
  
  stop: |
    Stop the instance after configuring it.
    
  snapshot: |
    Create a snapshot of the instance after configuring it.
  
  properties: |
    A map of properties, used for property substitution.
    These properties override global properties,
    and properties from included files.

  description: |
    This is not currently used.  You can put a description there for your own use.
    Or you can put a description in YAML comments.
    Putting it in a field will preserve it when going through config file migration.
  